name: Node CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  summarize:
    name: Generate API, README
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      - name: Generate files
        run: node scripts/summarize.mjs run
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Generate API and README summary [skip ci]"
          commit_user_name: robot_sunw31
          commit_user_email: sunw31@163.com
          commit_author: robot_sunw31 <sunw31@163.com>
      
